
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import oracle.net.aso.a;

/**
 *
 * @author ASUS
 */
public class Oteller extends javax.swing.JFrame {

    public String g, c, id, giris, cikis, text;
    public ArrayList<String> names;
    public static Connection conn;
    public static ResultSet rs;

    public static void ac() {
        //Connection conn ;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {

            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = (Connection) DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "SYSTEM", "SYSTEM");

        } catch (Exception e) {
            System.out.println("exception");
        }
    }

    public static void kapat() {
        Connection conn = null;
        try {

            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "SYSTEM", "SYSTEM");

            conn.close();
        } catch (Exception e) {
            System.out.println("exception");
        }

    }

    public Oteller() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    public Oteller(ArrayList<String> gelen) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        System.out.print(gelen.size() + "dir");

        if (gelen.size() == 1) {

            jPanel1.setVisible(true);
            jLabel1.setText(gelen.get(0));
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);

        } else if (gelen.size() == 2) {
            jPanel1.setVisible(true);
            jLabel1.setText(gelen.get(0));
            jPanel2.setVisible(true);
            jLabel2.setText(gelen.get(1));
            jPanel3.setVisible(false);

            jPanel4.setVisible(false);

        } else if (gelen.size() == 3) {
            jPanel1.setVisible(true);
            jLabel1.setText(gelen.get(0));
            jPanel2.setVisible(true);
            jLabel2.setText(gelen.get(1));
            jPanel3.setVisible(true);
            jLabel3.setText(gelen.get(2));
            jPanel4.setVisible(false);

        } else if (gelen.size() == 4) {
            jPanel1.setVisible(true);
            jLabel1.setText(gelen.get(0));
            jPanel2.setVisible(true);
            jLabel2.setText(gelen.get(1));
            jPanel3.setVisible(true);
            jLabel3.setText(gelen.get(2));
            jPanel4.setVisible(true);
            jLabel4.setText(gelen.get(3));

        } else {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            JOptionPane.showMessageDialog(null, "SEÇTİĞİNİZ ŞEHİRDE OTELİMİZ BULUNMAMAKTADIR");
        }
        //   jLabel2.setText((String) gelen.get(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        filtre = new javax.swing.JButton();
        acıkbüfe = new javax.swing.JCheckBox();
        odakahvaltı = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        bes = new javax.swing.JCheckBox();
        dort = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(242, 233, 201));

        filtre.setBackground(new java.awt.Color(153, 153, 153));
        filtre.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        filtre.setForeground(new java.awt.Color(102, 0, 102));
        filtre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/filter.png"))); // NOI18N
        filtre.setText("FİLTRELE");
        filtre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtreActionPerformed(evt);
            }
        });

        acıkbüfe.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        acıkbüfe.setText("AÇIK BÜFE");

        odakahvaltı.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        odakahvaltı.setText("ODA KAHVALTI");
        odakahvaltı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odakahvaltıActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("KONSEPT");

        bes.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        bes.setText("5");
        bes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besActionPerformed(evt);
            }
        });

        dort.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        dort.setText("4");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("YILDIZ SAYISI");

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 0, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/left-arrow.png"))); // NOI18N
        jButton5.setText("GERİ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setForeground(new java.awt.Color(249, 235, 202));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/looking-for-an-apartment.png"))); // NOI18N
        jButton1.setText("İNCELE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setForeground(new java.awt.Color(249, 235, 202));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/looking-for-an-apartment.png"))); // NOI18N
        jButton2.setText("İNCELE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jButton3.setBackground(new java.awt.Color(102, 0, 102));
        jButton3.setForeground(new java.awt.Color(249, 235, 202));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/looking-for-an-apartment.png"))); // NOI18N
        jButton3.setText("İNCELE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jLabel3))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jButton4.setBackground(new java.awt.Color(102, 0, 102));
        jButton4.setForeground(new java.awt.Color(249, 235, 202));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/looking-for-an-apartment.png"))); // NOI18N
        jButton4.setText("İNCELE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jLabel4))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bes)
                    .addComponent(jLabel5)
                    .addComponent(dort)
                    .addComponent(jLabel7)
                    .addComponent(odakahvaltı)
                    .addComponent(acıkbüfe)
                    .addComponent(filtre))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bes)
                .addGap(18, 18, 18)
                .addComponent(dort)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(odakahvaltı)
                .addGap(18, 18, 18)
                .addComponent(acıkbüfe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Oda_secimi s1 = new Oda_secimi();
        s1.setVisible(true);
        s1.g = giris;
        s1.c = cikis;
        //   s1.kisi_s=kisi;
        s1.otel_id = jLabel1.getText();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Oda_secimi s1 = new Oda_secimi();
        s1.setVisible(true);
        s1.g = giris;
        s1.c = cikis;
        // s1.kisi_s=kisi;
        s1.otel_id = jLabel2.getText();
        s1.mus_id = id;
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Oda_secimi s1 = new Oda_secimi();
        s1.setVisible(true);
        s1.g = giris;
        s1.c = cikis;
        //    s1.kisi_s=kisi;
        s1.otel_id = jLabel3.getText();
        s1.mus_id = id;
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Oda_secimi s1 = new Oda_secimi();
        s1.setVisible(true);
        s1.g = giris;
        s1.c = cikis;
        // s1.kisi_s=kisi;
        s1.otel_id = jLabel4.getText();
        s1.mus_id = id;
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void besActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_besActionPerformed

    private void filtreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtreActionPerformed

        ac();
        Statement stmt;
        //System.out.print(names.size());

        try {
            stmt = conn.createStatement();
            if (bes.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                }

                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            if (dort.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                }

                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            if (odakahvaltı.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            if (acıkbüfe.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            if (acıkbüfe.isSelected() && odakahvaltı.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or KONSEPT='oda kahvaltı'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            //-----------------------
            if (bes.isSelected() && dort.isSelected()) {

                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND OTEL_YILDIZ='4' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            //-----------------
            if (bes.isSelected() && odakahvaltı.isSelected()) {

                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "')  AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "')  AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "')  AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "')  AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            //-------------
            if (dort.isSelected() && acıkbüfe.isSelected()) {

                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            if (dort.isSelected() && odakahvaltı.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "')  AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "')  AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "')  AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "')  AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            //-------------
            if (bes.isSelected() && acıkbüfe.isSelected()) {

                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            //--------------44444444444444444444
            if (bes.isSelected() && acıkbüfe.isSelected() && dort.isSelected()) {

                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe'  or OTEL_YILDIZ='5' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='açık büfe' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            //------------
            if (bes.isSelected() && odakahvaltı.isSelected() && dort.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı'  or OTEL_YILDIZ='5' or OTEL_YILDIZ='4' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or OTEL_YILDIZ='4'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            if (bes.isSelected() && odakahvaltı.isSelected() && acıkbüfe.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı'  or OTEL_YILDIZ='5' or  KONSEPT='açık büfe' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or   KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5'  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or   KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);

                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            if (dort.isSelected() && odakahvaltı.isSelected() && acıkbüfe.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı'  or OTEL_YILDIZ='4' or  KONSEPT='açık büfe' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or   KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4'  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or   KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
            if (dort.isSelected() && bes.isSelected() && odakahvaltı.isSelected() && acıkbüfe.isSelected()) {
                if (names.size() == 1) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı'  or OTEL_YILDIZ='4' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe' ";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or OTEL_YILDIZ='5' or   KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 2) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or OTEL_YILDIZ='5'  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                } else if (names.size() == 3) {
                    if (text.equals("ANKARA")) {
                        String sql = " SELECT OTEL_İD FROM ANKARA_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or OTEL_YILDIZ='5' or   KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İSTANBUL")) {
                        String sql = " SELECT OTEL_İD FROM İSTANBUL_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    } else if (text.equals("İZMİR")) {
                        String sql = " SELECT OTEL_İD FROM İZMİR_OTEL  WHERE OTEL_İD IN('" + names.get(0) + "','" + names.get(1) + "','" + names.get(2) + "') AND KONSEPT='oda kahvaltı' or OTEL_YILDIZ='4' or OTEL_YILDIZ='5' or  KONSEPT='açık büfe'";
                        rs = stmt.executeQuery(sql);
                    }
                }
                ArrayList<String> array = new ArrayList<String>();
                while (rs.next()) {
                    array.add(rs.getString(1));
                }
                if (array.size() == 0) {
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                } else if (array.size() == 1) {
                    System.out.print(array.size());
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(false);
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 2) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);

                } else if (array.size() == 3) {
                    jPanel1.setVisible(true);
                    jLabel1.setText(array.get(0));
                    jPanel2.setVisible(true);
                    jLabel2.setText(array.get(1));
                    jPanel3.setVisible(true);
                    jLabel3.setText(array.get(2));
                    jPanel4.setVisible(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Oteller.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_filtreActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Ana_sayfa a = new Ana_sayfa();
        a.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void odakahvaltıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odakahvaltıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odakahvaltıActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oteller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oteller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oteller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oteller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Oteller a1 = new Oteller();
                a1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acıkbüfe;
    private javax.swing.JCheckBox bes;
    private javax.swing.JCheckBox dort;
    private javax.swing.JButton filtre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox odakahvaltı;
    // End of variables declaration//GEN-END:variables
}
